# ----------------------------------------------------------------------
# nuke-config — renders an aws-nuke (ekristen fork) YAML configuration
# from typed inputs. No AWS resources; just a string output and an
# optional local_file write. Caller invokes aws-nuke separately.
#
# The YAML schema this targets is documented at
# https://aws-nuke.ekristen.dev/config/. Filters are pass-through:
# whatever the caller puts in `var.filters` ends up under
# `accounts.<account_id>.filters` verbatim.
# ----------------------------------------------------------------------

locals {
  config_body = yamlencode({
    regions   = var.regions
    blocklist = var.blocklist
    accounts = {
      (var.account_id) = {
        filters = var.filters
      }
    }
  })

  header = trimspace(<<-EOT
    # aws-nuke (ekristen fork) configuration.
    # Generated by terraform-aws-bootstrap//modules/nuke-config — DO NOT EDIT.
    #
    # Account:  ${var.account_id}
    # Regions:  ${join(", ", var.regions)}
    #
    # Apply this stack to regenerate; run aws-nuke against the rendered
    # file (or the `yaml` output) — see https://aws-nuke.ekristen.dev/.
  EOT
  )

  yaml = "${local.header}\n\n${local.config_body}"
}

# When `var.output_path` is set, persist the YAML on disk as well as
# returning it via the output. count = 0 keeps the local provider out
# of the dependency graph entirely if the path isn't set.
resource "local_file" "this" {
  count = var.output_path == null ? 0 : 1

  filename        = var.output_path
  content         = local.yaml
  file_permission = "0644"
}
